### ISSUE TITLE
Hijacked process crashes

### ISSUE THREAD

**Issue by zashraf1337** [tklengyel/drakvuf#158]
The hijacked process crashes when trying to analyze

```
https://virustotal.com/en/file/9b2b035d54162a2596cb737373ba241c35f66c4b3bef77b82cebb9f595c551f0/analysis/
```

debug log:

```
DRAKVUF v0.3-27771ae
Init VMI on domID 148 -> XenWin7-1-clone
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
Reservation increased? 0 with new gfn: 0x10e2cd
Xen altp2m view created with idx: 1 idr: 2
Target PID 2884 with DTB 0x1a7f2000 to start 'C:\Users\John Smith\Desktop\test.exe'
Found PEB @ 0x7fffffdf000. LDR @ 0x77122640. INLOADORDER @ 0x332700.
Found module notepad.exe
Found module ntdll.dll
Found module kernel32.dll
        CreateProcessA @ 0x76e68840
Starting injection loop
Started DRAKVUF loop
CR3 cb on vCPU 1: 0x5e73c000
CR3 changed to 0x5e73c000
CR3 cb on vCPU 1: 0x4fb84000
CR3 changed to 0x4fb84000
CR3 cb on vCPU 0: 0x5d9c3000
CR3 changed to 0x5d9c3000
CR3 cb on vCPU 0: 0x187000
CR3 changed to 0x187000
CR3 cb on vCPU 0: 0x5d9c3000
CR3 changed to 0x5d9c3000
CR3 cb on vCPU 1: 0x5d5cf000
CR3 changed to 0x5d5cf000
CR3 cb on vCPU 0: 0x187000
CR3 changed to 0x187000
CR3 cb on vCPU 1: 0x187000
CR3 changed to 0x187000
CR3 cb on vCPU 1: 0x5e73c000
CR3 changed to 0x5e73c000
CR3 cb on vCPU 1: 0x187000
CR3 changed to 0x187000
CR3 cb on vCPU 0: 0x5d36b000
CR3 changed to 0x5d36b000
CR3 cb on vCPU 1: 0x5e73c000
CR3 changed to 0x5e73c000
CR3 cb on vCPU 0: 0x1a7f2000
CR3 changed to 0x1a7f2000
Thread @ 0xfffffa80028087f0. ThreadID: 2888
Breakpoint VA 0x76f09e6a -> PA 0x5b783e6a
Reservation increased? 0 with new gfn: 0x10e2ca
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x5b783e6a RPA 0x10e2cae6a Page 374659 for entry. 
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Breakpoint VA 0x76f09e6a -> PA 0x5b783e6a
Stack setup finished and return trap added @ 0x76f09e6a
Removing breakpoint trap from 0x5b783e6a.
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 0->1
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
INT3 event vCPU 0 altp2m:0 CR3: 0x4d83f000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1964. CR3 0x4d83f000.
INT3 received but CR3 (0x4d83f000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
Pre mem cb with vCPU 1 @ 0x5b783 0xe82 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe7a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe72 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe82 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe7a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 1 @ 0x5b783 0xe72 in view 1
Pre mem cb with vCPU 1 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 1 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 1
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 1 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 1
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
```

**Comment by tklengyel** [comment]
Update to the latest master branch, i think i fixed this issue yesterday.

**Comment by zashraf1337** [comment]
I believe I am not seeing injection happening and new process popping up
debug log
```
RAKVUF v0.3-27771ae
Init VMI on domID 195 -> XenWin7-1-clone
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
Reservation increased? 0 with new gfn: 0x14e272
Xen altp2m view created with idx: 1 idr: 2
Target PID 2884 with DTB 0x1a7f2000 to start 'C:\Users\John Smith\Desktop\cmd.exe'
Found PEB @ 0x7fffffdf000. LDR @ 0x77122640. INLOADORDER @ 0x332700.
Found module notepad.exe
Found module ntdll.dll
Found module kernel32.dll
        CreateProcessA @ 0x76e68840
Starting injection loop
Started DRAKVUF loop
CR3 cb on vCPU 1: 0x5e73c000
CR3 changed to 0x5e73c000
CR3 cb on vCPU 1: 0x187000
CR3 changed to 0x187000
CR3 cb on vCPU 0: 0x5d4d4000
CR3 changed to 0x5d4d4000
CR3 cb on vCPU 0: 0x1a7f2000
CR3 changed to 0x1a7f2000
Thread @ 0xfffffa80028087f0. ThreadID: 2888
Breakpoint VA 0x76f09e6a -> PA 0x5b783e6a
Reservation increased? 0 with new gfn: 0x14e271
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x5b783e6a RPA 0x14e271e6a Page 374659 for entry. 
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 0->1
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
RAX: 0x0
Removing breakpoint trap from 0x5b783e6a.
Removing memtrap for GFN 0x5b783, event @ 0x562421e2f930
Removing memtrap for GFN 0x14e271, event @ 0x562421c315f0
DRAKVUF loop finished
Finished with injection. Ret: 0
Process startup failed
close_vmi_drakvuf finished
```

**Comment by tklengyel** [comment]
Thats correct, in the log it even says startup failed. This means windows
won't execute the file via CreateProcessA.

**Comment by zashraf1337** [comment]
Note:

this does not happen with 
```
commit 58a1d8ba9c8de4a4d63ff4a8c1f8346b3d8d6112
Author: Tamas K Lengyel <tamas@tklengyel.com>
Date:   Wed May 25 11:48:40 2016 -0600

    64-bit injector optimization (#157)
```

but happens with:
```
commit dca7faab01c344eb3054379308d2fe5e9875dc80
Author: Tamas K Lengyel <tamas@tklengyel.com>
Date:   Thu May 26 19:44:52 2016 -0600

    Pause tweaking (#160)
```

Note when I am cloning from the original domu, that domu is in paused state - just fya

**Comment by tklengyel** [comment]
That's odd, #160 should have no affect on it. Can you check what happens if you unpause the domain after cloning and then start the injection?

**Comment by zashraf1337** [comment]
After running drakvuf on a domain, would you expect that when drakvuf runs ends the domain would be paused?

**Comment by tklengyel** [comment]
Yes, it should be paused.

**Comment by zashraf1337** [comment]
OK, so I think the first issue is that now it gets paused right away after the injection, which prevents the process from actually starting up. e.g. for preconfig.sh script it would actually create the cmd,exe but the domain would be paused so nothing would happen until the domain is unpaused. So perhaps we need to do a delay without putting the domain to sleep from injector code.

**Comment by tklengyel** [comment]
You mean injector is leaving the domain paused? That shouldn't be the case.

**Comment by zashraf1337** [comment]
I added some printf in xen_helper and this is what I see during injection
```
Finished with injection. Ret: 1
close_vmi_drakvuf finished
Injector starting cmd.exe /c <...> through PID 2884
xen_pause:
xen_resume: calling xc_domain_unpause
xen_force_resume:
xen_pause:
xen_resume: calling xc_domain_unpause
xen_pause:
xen_resume: calling xc_domain_unpause
Process startup success
xen_resume: calling xc_domain_unpause
```

**Comment by zashraf1337** [comment]
OK so the pausing issue is fixed, but the following sample still crashes the hijacked process, have you tried this sample? 
```
https://virustotal.com/en/file/9b2b035d54162a2596cb737373ba241c35f66c4b3bef77b82cebb9f595c551f0/analysis/
```

**Comment by zashraf1337** [comment]
Here is the log for the above VT sample
```
Xen altp2m view created with idx: 1 idr: 2
Target PID 2884 with DTB 0x1a7f2000 to start 'C:\Users\John Smith\Desktop\test.exe'
Found PEB @ 0x7fffffdf000. LDR @ 0x77122640. INLOADORDER @ 0x332700.
Found module notepad.exe
Found module ntdll.dll
Found module kernel32.dll
        CreateProcessA @ 0x76e68840
Starting injection loop
Started DRAKVUF loop
CR3 cb on vCPU 1: 0x5e73c000
CR3 changed to 0x5e73c000
CR3 cb on vCPU 1: 0x5cfe0000
CR3 changed to 0x5cfe0000
CR3 cb on vCPU 0: 0x1a7f2000
CR3 changed to 0x1a7f2000
Thread @ 0xfffffa80028087f0. ThreadID: 2888
Breakpoint VA 0x76f09e6a -> PA 0x5b783e6a
Reservation increased? 0 with new gfn: 0x13a0cf
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x5b783e6a RPA 0x13a0cfe6a Page 374659 for entry.
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 0->1
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
INT3 event vCPU 0 altp2m:0 CR3: 0x4d83f000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1964. CR3 0x4d83f000.
INT3 received but CR3 (0x4d83f000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
Pre mem cb with vCPU 0 @ 0x5b783 0xe82 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe7a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe72 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe82 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe7a in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe72 in view 1
Post mem cb @ 0x5b783
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1
Post mem cb @ 0x5b783
INT3 event vCPU 1 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 1
reset trap, switching 0->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
INT3 event vCPU 0 altp2m:0 CR3: 0x4da29000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1828. CR3 0x4da29000.
INT3 received but CR3 (0x4da29000) doesn't match target process (0x1a7f2000)
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 1->1
```

**Comment by zashraf1337** [comment]
Other hashes that are not working:
```
95a5f91931723a65dcd4a3937546da34
efc847ac17603a4c83d4b4a816bf75c7
039f40c230f3521d9120131081302a26
6a09c8d0b5497e4fa9bb4f62c8c77ffd
ec1c7c5506f394d2186ce67b895b2570
f6de770ad52015f18d0a2344815e408d
e3a3b10134de5bed53fedce53e33c284
1119b2bd8bf410a42fce70b44a30d385
5ffe2be78d4833bd2db4f1867e066140
73f69ad2e7bf41c5f976fb0eef0f9d77
5036448ed1a00bde4b38ab99a86aa6dc
7de393b4286292cf72fc087fa193771d
801dfc15c5142b25dd5f3b2f8d52efd2
cd7a72be9c16c2ece1140bc461d6226d
0d6c4d8a8b4756d604ae9743f1c038cd
f6bc2e58011f2c14c8ad9616e3b79639
b207743327ddd36ad136d428ab46197b
8bbb1250816fdf947d7395aef42b5f8a
```

**Comment by tklengyel** [comment]
@zashraf1337: so are these binaries still crash the hijacked process, or they fail to start with similar log as you posted before?

**Comment by zashraf1337** [comment]
This issue is only referring to the hijacked process being crashed. The fail to start thing just appeared when trying the new changes you made, but that has been taken care of with #163 so we are back to discussing the original issue which is the hijack process being crashed.

Can you try the following and let me know if you can reproduce? 
`https://virustotal.com/en/file/9b2b035d54162a2596cb737373ba241c35f66c4b3bef77b82cebb9f595c551f0/analysis/`

**Comment by tklengyel** [comment]
Can you send the binary to me in an encrypted zip with pw 'infected'? Thanks.

**Comment by tklengyel** [comment]
This is what I see when I start the process with injector:

> ./src/injector /share/rekall-profiles/windows7-sp1-x64.json windows7-sp1-x66-jenkins 2036 "C:\\Users\\MrX\\Downloads\\test.exe"
Init VMI on domID 7 -> windows7-sp1-x66-jenkins
Rekall profile: '_KPCR' has no 'PrcbData' member
Failed to find offset for _KPCR:PrcbData
Reservation increased? 0 with new gfn: 0x355b46
Xen altp2m view created with idx: 1 idr: 2
Injector starting C:\Users\MrX\Downloads\test.exe through PID 2036
Target PID 2036 with DTB 0x13bfe000 to start 'C:\Users\MrX\Downloads\test.exe'
Found PEB @ 0x7fffffd6000. LDR @ 0x77d32640. INLOADORDER @ 0x302600.
Found module taskmgr.exe
Found module ntdll.dll
Found module kernel32.dll
	CreateProcessA @ 0x77b78840
Starting injection loop
Started DRAKVUF loop
CR3 cb on vCPU 1: 0x23dcf000
...snip...
CR3 changed to 0x13bfe000
Thread @ 0xfffffa8003215b60. ThreadID: 2040
Breakpoint VA 0x779f9e6a -> PA 0x27fe6e6a
Reservation increased? 0 with new gfn: 0x355b44
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
		Trap added @ PA 0x27fe6e6a RPA 0x355b44e6a Page 163814 for entry. 
Got return address 0x779f9e6a from trapframe and it's now trapped!
INT3 event vCPU 1 altp2m:0 CR3: 0x13bfe000 PA=0x27fe6e6a RIP=0x779f9e6a
INT3 Callback @ 0x779f9e6a. PID 2036. CR3 0x13bfe000.
Switching altp2m and to singlestep on vcpu 1
reset trap, switching 0->1
INT3 event vCPU 0 altp2m:0 CR3: 0x13bfe000 PA=0x27fe6e6a RIP=0x779f9e6a
INT3 Callback @ 0x779f9e6a. PID 2036. CR3 0x13bfe000.
RAX: 0x1
Injected PID: 1068. TID: 1272
Removing breakpoint trap from 0x27fe6e6a.
Removing memtrap for GFN 0x27fe6, event @ 0x2029cb0
Removing memtrap for GFN 0x355b44, event @ 0x2029f00
DRAKVUF loop finished
Finished with injection. Ret: 1
Process startup success
close_vmi_drakvuf finished

**Comment by zashraf1337** [comment]
Have you tried running drakvuf on it with say `syscalls`?

**Comment by tklengyel** [comment]
Yes, it seems to be working fine, so I'm unable to reproduce the issue.

**Comment by tklengyel** [comment]
Try the latest version from git, maybe I've fixed something along the way that resolved this issue too.

**Comment by tklengyel** [comment]
@zashraf1337: Can you check if the issue is still happening with the latest version of LibVMI from the drakvuf branch & DRAKVUF on Xen 4.7?

**Comment by zashraf1337** [comment]
This is still happening, here is what I am doing for an isolated reproduction of the issue.

```
root@zmal01:/malware_finished/ec1c7c5506f394d2186ce67b895b2570# xl list
Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0  4095     4     r-----    5286.2
XenWin7                                      8  3000     2     --p---       0.0

root@zmal01:/malware_finished/ec1c7c5506f394d2186ce67b895b2570# PATH=/home/zmal/Dev/drakvuf/src:/home/zmal/Dev/drakvuf/tools:$PATH;xl destroy XenWin7-1-clone ;lvremove -f /dev/XenVolG/XenWin7-1-clone;lvcreate -s -n /dev/XenVolG/XenWin7-1-clone  -L16G /dev/XenVolG/XenWin7;xl save -c XenWin7 /tmp/drakvuf_pipe_XenWin7-1-clone 2>&1 | /usr/local/sbin/xl restore -p -e /tmp/XenWin7-1-clone.config /tmp/drakvuf_pipe_XenWin7-1-clone;date;id=`xl domid XenWin7-1-clone`;echo "id;$id";echo "file:$file";preconfig.sh /root/XenWin7.rekall.json $id 2884 1 /malware_processing $file /malware_finished/

root@zmal01:/malware_finished/ec1c7c5506f394d2186ce67b895b2570# drakvuf -r /root/XenWin7.rekall.json -d $id -i 2884 -e "C:\Users\John Smith\Desktop\test.exe" -D /malware_finished/ec1c7c5506f394d2186ce67b895b2570 -o csv -t 30 2>&1 | tee drakvuf.log


```
This causes the hijacked process notepad to crash as shown in the attached image.

![image](https://cloud.githubusercontent.com/assets/6955094/16825967/57f88eee-4947-11e6-94e6-b7445faee828.png)

**Comment by tklengyel** [comment]
Interesting, no clue why that happens. Anyhow, if injecting cmd.exe doesn't crash it then maybe inject "cmd.exe /c /path/to/$file", instead of directly the file itself.

**Comment by zashraf1337** [comment]
@tklengyel you have tried to reproduce it on x64 right?

**Comment by tklengyel** [comment]
I did, I can't reproduce it. The PR tester has consistently passing injection tests too so I don't have a good grasp on the too cause at the moment.

**Comment by zdzhjx** [comment]
If run these lines, everything will be ok.

798 
799     vmi_set_vcpureg(injector->vmi, injector->saved_rsp, RSP, info->vcpu);
800     vmi_set_vcpureg(injector->vmi, injector->saved_rax, RAX, info->vcpu);
801     vmi_set_vcpureg(injector->vmi, injector->saved_rcx, RCX, info->vcpu);
802     vmi_set_vcpureg(injector->vmi, injector->saved_rdx, RDX, info->vcpu);
803     vmi_set_vcpureg(injector->vmi, injector->saved_r8, R8, info->vcpu);
804     vmi_set_vcpureg(injector->vmi, injector->saved_r9, R9, info->vcpu);
805 
806     PRINT_DEBUG("RAX: 0x%lx\n", rax);

so, I think it is the problem of trap on RIP address, how to debug it?  @tklengyel   

Thanks.

**Comment by zashraf1337** [comment]
@tklengyel OK I can reproduce it consistently so will debug and keep sharing thoughts, if you have an idea to try let me know.

@zdzhjx thanks. Which file is this?

**Comment by zashraf1337** [comment]
DEBUG INFO:

so for the case when I fire cmd.exe showing setting BP on RIP from trap frame and then breaking into the INT3 CB, the logs are:

```
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x5b783e6a RPA 0x15e3f1e6a Page 374659 for entry.
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 1 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Switching altp2m and to singlestep on vcpu 1
reset trap, switching 0->1
INT3 event vCPU 1 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
RAX: 0x1
Injected PID: 2616. TID: 1232
Removing breakpoint trap from 0x5b783e6a.
Removing memtrap for GFN 0x5b783, event @ 0x55c538332a90
Removing memtrap for GFN 0x15e3f1, event @ 0x55c538332970
DRAKVUF loop finished
```

For the failing case logs are:
```
Thread @ 0xfffffa80028087f0. ThreadID: 2888
Breakpoint VA 0x76f09e6a -> PA 0x5b783e6a
Reservation increased? 0 with new gfn: 0x1de3f1
Copied trapped page to new location
Activating remapped gfns in the altp2m views!
                Trap added @ PA 0x5b783e6a RPA 0x1de3f1e6a Page 374659 for entry.
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 0->1

```

so the first INT3 trap *is hit* in both case but for the failing case the second INT3 hit does not happen on the hijacked process.

```
Got return address 0x76f09e6a from trapframe and it's now trapped!
INT3 event vCPU 0 altp2m:0 CR3: 0x1a7f2000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 2884. CR3 0x1a7f2000.
Switching altp2m and to singlestep on vcpu 0
reset trap, switching 0->1
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1: r--
Post mem cb @ 0x5b783 vCPU 0
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1: r--
Post mem cb @ 0x5b783 vCPU 0
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1: r--
Post mem cb @ 0x5b783 vCPU 0
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1: r--
Post mem cb @ 0x5b783 vCPU 0
Pre mem cb with vCPU 0 @ 0x5b783 0xe6a in view 1: r--
Post mem cb @ 0x5b783 vCPU 0
INT3 event vCPU 0 altp2m:0 CR3: 0x4d83f000 PA=0x5b783e6a RIP=0x76f09e6a
INT3 Callback @ 0x76f09e6a. PID 1964. CR3 0x4d83f000.
INT3 received but CR3 (0x4d83f000) doesn't match target process (0x1a7f2000)
```

It happens first on the PID 1964 which is taskhost.exe and then happens on other processes but not the hijacked process.

I wonder if mishandling from one of these mem cb is causing the hijacked process to crash?

**Comment by tklengyel** [comment]
It might be that the thread that get's hijacked was in an unusable state (being killed or exiting or something). Extending the injector to take the Thread ID as an input as well and only hijack a given thread could definitely reduce the scope of when this issue arises.

**Comment by zashraf1337** [comment]
FYA same thread is hijacked in both passing (cmd) and failing (malware sample) case

**Comment by tklengyel** [comment]
@zashraf1337: interesting, the fact that the return address is getting hit in another process and not the target is the key information here. Something goes wrong after that happens and we seem to miss when the target process returns. At that point we need to fix up the stack as if nothing happened and since we don't do that the process crashes.

**Comment by tklengyel** [comment]
I think the root cause of this problem may have had been the use of `vmi_set_vcpureg` at the cleanup phase. I had been oblivious to the fact that this function requires the VM to be paused, not just the vCPU where the register is being set. This has been recently solved by not using this function anywhere in the injector in PR #243.

@zashraf1337 Could you check if you can still trigger this problem?

**Comment by masthoon** [comment]
@tklengyel I had some issues with the injector too.
In [injector_int3_cb line 751](https://github.com/tklengyel/drakvuf/blob/044a02d2a2e5493d45295b6bf41dc5e0de29684b/src/libinjector/injector.c#L751), you assume that the breakpoint was triggered by the return of CreateProcessA. 
But it can be triggered by another thread and both threads might crash due to the restoring of registers on the wrong thread.

I fixed it by storing **threadid** in *injector->target_tid* after the hijacking of the thread (when *injector->hijacked* is set to 1) and by checking the value of threadid before line *751*.

**Comment by tklengyel** [comment]
@masthoon: yea, I remember having that issue and I thought I fixed it.. either I never ended up committing that patch or I've removed it during one of the cleanups O.o Do you want to create a PR for it?

**Comment by masthoon** [comment]
The patch seems good, thank you.
I don't know if this patch resolves @zashraf1337's problem.
